### PR TITLE
Grammar update in Readme file

### PR DESCRIPTION
**Pull request by aryman1503**

### CODE REVIEW

**Comment by ManoMarks** [comment]
Made comments, please revise the first one and I'll approve

**Comment by aryman1503** [comment]
Ok I will do the same.

**Comment by ManoMarks** [comment]
There's actually a few more issues with the PR.

**Comment by aryman1503** [comment]
Okay

**Comment by ManoMarks** [comment]
Marking as outdated as fixes were not made to the PR

**Pull request closed without merging**
